In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

TOPICS COVERED

1.Creating arrays

2.List vs ndarray

3.ndarrayvs attributes

4.Indexing and slicing

INTRODUCTION TO  NUMPY

NumPy is one of the most important foundational packages for numerical computing in Python

It provides a high performance multidimensional array object and tools for working with these arrays.

**DIFFERENCE B/W ITEMSIZE AND SIZE**

The itemsize attribute in NumPy provides information about the memory consumption of individual elements within a NumPy array.This value is determined by the data type (dtype) of the array. 

The size attribute in NumPy returns the total number of elements in a NumPy array. This attribute provides a single integer value representing the count of all elements within the array, regardless of its dimensions or shape. 



In [7]:
import numpy 
Sneha=numpy.array([[21,23,22,21,24],[56,36,78,88,78]],dtype=float)
#my array=numpy.array([1,2,3,4])
print(Sneha)
print(Sneha.shape)#row,col
print(Sneha.size) # no of elements
print(Sneha.itemsize)#memory used by one element(datatype of array)
print(Sneha.ndim)#dimensions 1d,2d ,3d

[[21. 23. 22. 21. 24.]
 [56. 36. 78. 88. 78.]]
(2, 5)
10
8
2


**NumPy AS np**

1.NumPy is usually under the np alias

alias:In Python alias are an alternate name for reffering to the same thing







In [15]:
import numpy as np
Myarray=np.array(['green','black','blue'])
print(Myarray)
print(Myarray.shape)
print(Myarray.size)
print(Myarray.itemsize)
print(Myarray.ndim)


['green' 'black' 'blue']
(3,)
3
20
1


In [17]:
import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])
print(arr_3d.shape)#row,col,width
print(arr_3d.ndim)


(2, 2, 3)
3


CHECKING NUMPY VERSION

In [18]:
numpy.__version__

'1.26.4'

**Creating Arrays**


1.the array object in Numpy is called ndarray

2.we can create a numpy ndarray object by using the array()function



In [23]:
import numpy as np
arr=np.ones((3,3))
arr2=np.zeros((2,2))#null matrix

print(arr)
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


**Why do we use python numpy even if we already have python list?**

we use numpy array instead of list because:

less memory

fast

convenient to understand it
 

In [18]:
import numpy as np
print(np.full((2,2),7))
print(np.eye(3))#identity matrix of order 3
print(np.arange(0,10,2))#starting value,ending value(excluded),stepsize
print(np.linspace(0,2,5))#starting value,ending value(included),no of values having same difference
print(np.random.rand(2,3))#taking float values b/w 0 and 1
print(np.random.randint(0,10,(3,3)))#returns integer values between 0 and 10 
print(np.random.seed(23))
print(np.random.randint(0,10,(3,3)))



[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[[0.39244247 0.61805235 0.41193009]
 [0.00246488 0.88403218 0.88494754]]
[[0 9 9]
 [3 1 7]
 [4 1 1]]
None
[[3 6 8]
 [9 6 8]
 [7 9 3]]
[[6 1 2]
 [5 5 0]
 [5 0 9]]


*USE OF SEED()FUNCTION*

sets the seed value .

 It ensures that random values generated are same for every run.

  **generating random numbers without using the .seed() method results in different outputs on each run, whereas using it ensures consistent results every time


*AXIS HANDLING*****

Axis 0:operates down columns

Axis 1:operates across rows

In [9]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,5]])
print('column wise sum:',arr1.sum(axis=0))
print('crow wise mean:',arr1.mean(axis=1))
print('max of each row:',arr1.max(axis=1))
print('Transpose:\n',arr1.T)
print('Reshape to 1D:',arr1.flatten())#converts every 2d or 3d matrix/array into 1D array 

column wise sum: [4 6 8]
crow wise mean: [2. 4.]
max of each row: [3 5]
Transpose:
 [[1 3]
 [2 4]
 [3 5]]
Reshape to 1D: [1 2 3 3 4 5]
